# Select base image
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy dependency files inside of the directory
COPY ./pubby-frontend/package.json ./
COPY ./pubby-frontend/package-lock.json ./

# Install the dependencies
RUN npm install

# Copy everything else inside working directory
COPY ./ ./

WORKDIR /app/pubby-frontend

# Create a production-ready build
RUN npm run build

#Expose port 80
EXPOSE 80

# Run the app
CMD [ "npm", "run", "serve" ]