# Select base image
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy dependency files inside of the directory
COPY package.json ./
COPY package-lock.json ./

# Install the dependencies
RUN npm install

# Copy everything else inside working directory
COPY ./ ./

# Create a production-ready build
RUN npm run build

# Install serve dependency
RUN npm install -g serve

#Expose port 3000
EXPOSE 3000

# Run the app
CMD [ "serve", "-s", "build" ]